CREATE TABLE categorias
  (
    NUMCATEGORIA INTEGER PRIMARY KEY,
    NOMBRE       VARCHAR(50)
  );
CREATE TABLE productos
  (
    ARTICULO     VARCHAR(20) PRIMARY KEY,
    DESCRIPCION  VARCHAR(70),
    NUMCATEGORIA INTEGER,
    PRECIO FLOAT,
    CONSTRAINT FKPRODUCTOSCATEGORIAS FOREIGN KEY (NUMCATEGORIA) REFERENCES CATEGORIAS (NUMCATEGORIA)
  );
CREATE TABLE ESTADOS
  (
    ESTADO      VARCHAR(2) PRIMARY KEY,
    NOMBRE      VARCHAR(40),
    ABREVIATURA VARCHAR(6),
    PAIS        VARCHAR(5)
  );
CREATE TABLE MUNICIPIOS
  (
    MUNICIPIO INTEGER PRIMARY KEY,
    NOMBRE    VARCHAR(90),
    ESTADO    VARCHAR(2),
    CONSTRAINT FKESTADOSMUNICIPIOS FOREIGN KEY (ESTADO) REFERENCES ESTADOS (ESTADO)
  );
CREATE TABLE TIPOSASENTAMIENTOS
  (
    TIPO               INTEGER PRIMARY KEY,
    NOMBREASENTAMIENTO VARCHAR(50)
  );
CREATE TABLE COLONIASASENTAMIENTOS
  (
    NUMERO           INTEGER PRIMARY KEY,
    NOMBRE           VARCHAR(90),
    TIPOASENTAMIENTO INTEGER,
    CPOSTAL          VARCHAR(5),
    MUNICIPIO        INTEGER,
    CONSTRAINT FKCOLONIASMUNICIPIO FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIOS (MUNICIPIO),
    CONSTRAINT FKCOLONIASTIPOASENTAMIENTO FOREIGN KEY (TIPOASENTAMIENTO) REFERENCES TIPOSASENTAMIENTOS (TIPO)
  );
CREATE TABLE TIPOSCLIENTES
  (
    TIPO        CHAR(1) PRIMARY KEY,
    DESCRIPCION VARCHAR2(60)
  );
CREATE TABLE CLIENTES
  (
    RFC               VARCHAR2(14) PRIMARY KEY,
    NOMBRERAZONSOCIAL VARCHAR2(160),
    TIPO              CHAR(1),
    SEXO              CHAR(1),
    FECHANACIMIENTO   DATE,
    DIRECCION         VARCHAR2(160),
    ACTIVIDAD         VARCHAR2(160),
    COLONIA           NUMBER,
    EMAIL             VARCHAR2(160),
    TELEFONO          VARCHAR2(14),
    NUMERO            NUMBER UNIQUE,
    FREGISTRO         DATE,
    CONSTRAINT FKCOLONIASCLIENTES FOREIGN KEY (COLONIA) REFERENCES COLONIASASENTAMIENTOS (NUMERO),
    CONSTRAINT FKTIPOCLIENTES FOREIGN KEY (TIPO) REFERENCES TIPOSCLIENTES (TIPO)
  ) ;
CREATE TABLE TIENDAS
  (
    NOTIENDA    NUMBER PRIMARY KEY,
    NOMBRE      VARCHAR2(90),
    FECHAINICIO DATE,
    COLONIA     NUMBER,
    CONSTRAINT FKTIENDASCOLONIAASENTAMIENTOS FOREIGN KEY (COLONIA) REFERENCES COLONIASASENTAMIENTOS (NUMERO)
  );
CREATE TABLE EMPLEADOS
  (
    NOEMPLEADO      NUMBER PRIMARY KEY,
    PATERNO         VARCHAR2(30),
    MATERNO         VARCHAR2(30),
    NOMBRE          VARCHAR2(30),
    SEXO            CHAR(1),
    FECHANACIMIENTO DATE,
    FECHAINGRESO    DATE,
    TIENDA          NUMBER,
    COLONIA         NUMBER,
    FREGISTRO       DATE,
    CONSTRAINT FKTIENDAS FOREIGN KEY (TIENDA) REFERENCES TIENDAS (NOTIENDA) ENABLE,
    CONSTRAINT FKCOLONIAASENTAM FOREIGN KEY (COLONIA) REFERENCES COLONIASASENTAMIENTOS (NUMERO)
  );
CREATE TABLE VENTAS
  (
    NOVENTA  NUMBER PRIMARY KEY,
    FECHA    DATE,
    CLIENTE  NUMBER,
    EMPLEADO NUMBER,
    TIENDA   NUMBER,
    TOTAL FLOAT,
    CONSTRAINT FK_VENTASCLIENTES FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (NUMERO),
    CONSTRAINT FK_EMPLEADOSVENTAS FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS (NOEMPLEADO),
    CONSTRAINT FK_VENTASTIENDAS FOREIGN KEY (TIENDA) REFERENCES TIENDAS (NOTIENDA)
  );
CREATE TABLE DETALLEVENTAS
  (
    NOVENTA NUMBER,
    CLAVE   VARCHAR2(20),
    CANTIDAD FLOAT,
    PRECIO FLOAT,
    IMPORTE FLOAT,
    CONSTRAINT FK_NOVENTA FOREIGN KEY (NOVENTA) REFERENCES VENTAS (NOVENTA),
    CONSTRAINT FK_CLAVEPRODUCTO FOREIGN KEY (CLAVE) REFERENCES PRODUCTOS (ARTICULO)
  );
CREATE TABLE FACTURAS
  (
    NOFACTURA  NUMBER PRIMARY KEY,
    FECHA      DATE,
    NOVENTA    NUMBER,
    RFCCLIENTE VARCHAR2(14),
    CONSTRAINT FKFACTURASVENTAS FOREIGN KEY (NOVENTA) REFERENCES VENTAS (NOVENTA),
    CONSTRAINT FKFACTURASCLIENTES FOREIGN KEY (RFCCLIENTE) REFERENCES CLIENTES (RFC)
  );
